# Generated by Django 3.1.7 on 2021-04-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_subcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='NULL', upload_to='users_img/'),
        ),
    ]
