# Generated by Django 3.1.7 on 2021-04-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210427_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomment',
            name='anime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.anime'),
            preserve_default=False,
        ),
    ]
