# Generated by Django 3.1.7 on 2021-04-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210427_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='anime',
        ),
    ]
