# Generated by Django 3.1.7 on 2021-06-16 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210616_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='manga',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.manga'),
            preserve_default=False,
        ),
    ]
