# Generated by Django 3.1.7 on 2021-06-16 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_anime_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='manga',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.manga'),
        ),
    ]
