# Generated by Django 3.1.7 on 2021-06-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210616_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterfiles',
            name='page_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
