# Generated by Django 3.1.7 on 2021-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210513_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
