# Generated by Django 3.1.7 on 2021-05-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_anime_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(default='NULL', upload_to='posters/'),
        ),
    ]
