# Generated by Django 3.1.7 on 2021-04-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('studio_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('studio_name', models.CharField(max_length=64)),
            ],
        ),
    ]
