# Generated by Django 3.1.7 on 2021-04-23 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('commented_date', models.DateField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ViewStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.viewstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('subcomment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('commented_date', models.DateField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.category')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.status'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.studio'),
        ),
    ]
